---
# tasks file for ansible-role-postfix
- name: install postfix package
  yum:
    name:
      - postfix

- name: copy postfix conf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
  notify: restart postfix service

- name: start postfix service
  service:
    name: postfix
    state: started
    enabled: yes
  tags: haproxy
